print("Welcome to the tip calculator.")
bill = float(input("What was the total bill? $"))
people = int(input("How many people to split the bill? "))
tip = int(input("What percentage tip would you like to give? 10, 12, or 15? "))
total = round((bill / people) * (1 + (tip / 100)), 2)
total = "{:.2f}".format(total)
print(f"Each person should pay: ${total}")